version: '3.8'
services:
    db:
      image: mongo
      container_name: mongodb
      restart: always
      enviroment:
        - MONGO_INITDB_ROOT_USERNAME_=dio
        - MONGO_INITDB_ROOT_PASSWORD_=dio
      ports:
        - "27017:27017"
      volumes:
        - mongodata:/data/db
volumes:
  mongodata: